name: Deploy SolidJS App

on:
  push:
    branches:
      - main  # Deploy on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally
        
      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Verify build output
        run: ls -al ./dist  # List contents of the build folder to verify it exists

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
